- includes/plugins.php
With the current state of experience plugin it removes stream menu item and don't give any choice making it not able to use on a client  site. This PR adds a filter which allows to keep stream menu item and removes it in default state.
> Add filter to remove stream menu item

- assets/css/admin.css
- includes/admin-bar.php
The svg painter script needs a base64 encoded admin bar icon to be able to change the icon color depending on the admin color scheme.
_Caveat:_ Unfortunately, on the default theme, core passes an incorrect icon color to svg painter. The icon will be slightly too dark ([related WordPress Trac ticket](https://core.trac.wordpress.org/ticket/39261)). Until that issue is fixed, the only way to add a properly colored icon appears to be using an icon font.
Fixes #20
> Use base64 encoded svg for admin bar icon

- includes/plugins.php
When a string is wrapped in single quotes but contains a JS escape sequence (like `\n`) and run through `esc_js()`, the slashes get stripped instead of converted to their proper sequence. In this case, that means a message that contains `dashboard.nnAre you sure` instead of a line break.
Converting the string quotes to double-quotes enables the escape sequence as expected.
Fixes #29.
> Fix escaped newline characters in JS

- 10up-experience.php
- includes/gutenberg.php
- Adds toggle to the 'Writing' settings screen to use the 'Classic' editor instead of Gutenberg to easily toggle between sites and prepare sites for the release of WP 5.0. 
- Disables Gutenberg for WP 5.0+ as well as any site using the Gutenberg plugin using the hooks described at https://make.wordpress.org/core/2018/10/30/block-editor-filters/
> Add 'Use Classic Editor' Toggle

- 10up-experience.php
- composer.json
Changes:
- Adds failsafes if temporary loss of database connection causes required options to be stored in the `notoptions` cache.
> Release 1.5

- 10up-experience.php
- includes/option-failsafes.php
Removes option failsafe feature from execution.  Indicates approach to feature is being reevaluated.
Fixes #54 
Re-opens possibility of database connection errors storing `siteurl` and `home` in the `$notoptions` cache.  Risk of bringing down a site.
#54 
- Removes required options feature while approach is being reevaluated.
> Remove Option Failsafes

- 10up-experience.php
- includes/support-monitor-debug.php
- includes/support-monitor.php
Add debugger functionality to the 10up Support Monitor. By setting define( 'SUPPORT_MONITOR_DEBUG', true ); in wp-config.php this will create a log CPT for logging all messages sent to the support monitor API.
> Introduce support monitor debug logic

- 10up-experience.php
- includes/classes/Headers/Headers.php
set x-frame-options to SAMEORIGIN to avoid clickjacking attacks
Helps prevents clickjacking attacks.
Could cause issues if you are embedding the site on another site.
Manually look at the headers that are getting set.
Adds protection against clickjacking attacks.
> set x-frame-options to SAMEORIGIN to avoid clickjacking attacks

- includes/classes/Authentication/Passwords.php
Fix a esc_html__() call.
n/a
Closes #71 
Fix a call to esc_html__() in the weak password check
> Fix a esc_html__ call

- includes/classes/SupportMonitor/Monitor.php
Strengthens detection of an external object cache.
Some plugins, like Object Cache Pro (formerly Redis Cache Pro) do not set the `$_wp_using_ext_object_cache` global, or at least detection using that method was failing.
Stronger object cache detection.
None
> Strengthens detection of an external object cache

- includes/classes/SupportMonitor/Monitor.php
Updates the support monitor queued messages to include a message that triggers a web vitals test be run if the site is denoted as the production environment.
Adds support for notifying support monitor users of:
- Largest Contentful Paint
- Cumulative Layout Shift
- First Input Delay
- First Contentful Paint 
see https://web.dev/vitals/
none
- Adds a support monitor message to trigger [web vital ](https://web.dev/vitals/) reporting on production environments.
> Trigger Web Vital reporting with Support Monitor on Production environments

- includes/classes/Plugins/Plugins.php
Removes the code that was hiding the stream admin menu links.
Makes it easier to find the stream plugin dashboard. 
1. Install and Activate stream plugin
2. If logged in as an admin the stream menu item should appear below the dashboard one.
Resolves #88 
Removes logic that was hiding the stream admin menu item.
> Unhide Stream Menu Link

- includes/classes/Authors/Authors.php
This PR addresses the bug reported at #78 where users get redirected to the homepage when trying to filter the WP List Post table by a user that has a 10up email address. 
Allows 10up users to filter content in the WordPress admin that they have authored. This comes in handy when you're trying to delete any test post you might have made or when you want to attribute all your content to someone else. 
None
1. Create a user capable of creating posts
2. Assign an email address with the domain of 10up.com or get10up.com
3. Create a few post while logged in as the new user
4. Navigate to the All Post screen in the WordPress admin
5. Click on the author name of the newly created users
6. You should see all the post you just created and not get directed to the homepage
**If you try and view that …
> Fix Filtering WP List Table Views by 10up Author

- includes/classes/Gutenberg/Gutenberg.php
The block-based widgets editor is enabled in WordPress 5.8 by default. The PR uses the provided filter in https://make.wordpress.org/core/2021/06/29/block-based-widgets-editor-in-wordpress-5-8/ to disable the block editor in Widgets screen. 
- Should a new option to disable Widgets block editor be added in `Settings` > `Writing`?
- Automatically disable block editor in Widgets screen if following checkbox is selected.
N/A
- Disable block editor for widgets added in 5.8
> Disable widgets block editor

- README.md
- includes/classes/Authentication/Passwords.php
Addresses issue https://github.com/10up/10up-experience/issues/80 where a fatal error occurred during saving a profile if the mbstring PHP extension wasn't installed on the server.
Checks for mbstring function before trying to use the external dependency Zxcvbn, which was causing the issue.
Also adds documentation to let users know about the mbstring extension requirement in the README for password strength checker to work.
- Disabled mbstring extension in local PHP environment
- Saved profile on master branch with extension disabled and verified fatal error occurs.
- Switched to branch with fixes
- Saved profile and verified fatal didn't appear.
> Fix check mbstring

- 10up-experience.php
- includes/classes/API/API.php
- includes/classes/AdminCustomizations/Customizations.php
- includes/classes/Authentication/Passwords.php
- includes/classes/Authentication/Usernames.php
- includes/classes/Authors/Authors.php
- includes/classes/Gutenberg/Gutenberg.php
- includes/classes/Headers/Headers.php
- includes/classes/Notifications/Welcome.php
- includes/classes/Plugins/Plugins.php
- includes/classes/PostPasswords/PostPasswords.php
- includes/classes/SSO/SSO.php
- includes/classes/Singleton.php
- includes/classes/SupportMonitor/ActivityLog.php
- includes/classes/SupportMonitor/Debug.php
- includes/classes/SupportMonitor/Monitor.php
> As of PHP 8.1.0, when a method using static variables is inherited (but not overridden), the inherited method will now share static variables with the parent method. This means that static variables in methods now behave the same way as static properties. [[Source](https://www.php.net/manual/en/language.variables.scope.php#language.variables.scope.static)]
Because of this change, the `static $instance` in the Singleton abstract class's `instance` method was going to be shared between all classes that inherit from Singleton. As a result, the instance would be set to the first class whose `instance` method is called, and none of the other classes would be created.
This converts the class to a trait, which essentially gives each Singleton class its own instances of the `instance` static …
> Convert the Singleton class to a trait for PHP 8.1. compatibility

- includes/classes/SSO/SSO.php
Checks that `$REQUEST['redirect_to']` is a string before using it inside the conditional.
Closes #136 
1. Checkout branch in wp-content/plugins directory
2. Activate the plugin
3. Go to the login screen
4. Login with Single Sign On and get into the admin
5. Login with Single Sign On and get rejected
> Fixed - SSO: check that `$REQUEST['redirect_to']` is a string before using it inside the conditional.
Props @claytoncollie
> SSO: check that `$REQUEST['redirect_to']` is a string before using it inside the conditional

- includes/classes/AdminCustomizations/Customizations.php
This change fixes PHP 8.2 deprecation notices
```
Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /Users/claytoncollie/www/10upexperience/app/public/wp-includes/functions.php on line 7053
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /Users/claytoncollie/www/10upexperience/app/public/wp-includes/functions.php on line 2165
Deprecated: strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/claytoncollie/www/10upexperience/app/public/wp-admin/admin-header.php on line 36
```
1. Create a fresh install of WordPress
2. Clone repository and checkout branch
3. Set `WP_DEBUG` and `WP_DEBUG_DISPLAY` to `true`
4. Visit the wp-admin to look for the errors
5. …
> Add parent menu slug to `add_submenu_page` to avoid PHP 8.2 deprecation notices

- includes/classes/SupportMonitor/Monitor.php
We've seen an issue where ElasticPress filters are throwing out the 10up user queries. When the data is fed back to Support Monitor, it can be incorrect, causing issues with the SM alerting.
To get around this, we should disable ElasticPress on any user queries made within the SupportMonitor module, allowing WordPress to handle these queries in the standard way.
Run a SM report and ensure that the query isn't running through EP.
> Changed - 10up User reporting to Support Monitor now bypasses ElasticPress.
Props @darylldoyle, @ivanlopez, @hugosolar
> Don't use EP for Support Monitor Queries

- README.md
- includes/classes/Authentication/Passwords.php
Verify new password against the [Have I Been Pwned API](https://haveibeenpwned.com/API/v3) during password change (on profile or via reset process)
Closes [#77](https://github.com/10up/10up-experience/issues/77)
**Changing password through profile**
1. Login to WP and access you profile
2. Scroll down to "Set New Password" and enter something in a breach (e.g. `london123`)
3. Scroll down to the "Update Profile" button
4. If need be, remove the `disabled` attribute on the Update Profile button - this is added through JS when a "weak" password is identified
5. Save and confirm you see the error: "The password entered may have been included in a data breach and is not considered safe to use. Please choose another." - note you may also see another error stating "Password must be medium …
> Check haveibeenpwned API during password reset and account creation

- includes/classes/Plugins/Plugins.php
VIP have their own plugin update notification notifications, see: https://github.com/Automattic/vip-go-mu-plugins/blob/develop/codebase-manager/plugins/plugins-manager.php#L65-L77
As they run theirs on the same hook as us, it results in duplicate notices being shown. As such, we should bail early from our logic and use theirs.
**Before**
**After**
Closes #160
Ensure that update notices are only shown once on VIP sites.
* Fixed - Issue with duplicate update notices in VIP.
Props @darylldoyle
> Don’t render the plugin update notices on VIP as they’re duplicated

- README.md
- includes/classes/SupportMonitor/Monitor.php
Allow defining support monitor constants to override settings. Support has been added for both network activation and single-site activation.
New constants that were introduced.
1. `SUPPORT_MONITOR_ENABLE`
2. `SUPPORT_MONITOR_API_KEY`
3. `SUPPORT_MONITOR_SERVER_URL`
Closes #161 
**Default View:**
**View with Constants Set**
```php
define( 'SUPPORT_MONITOR_ENABLE', 'yes' );
define( 'SUPPORT_MONITOR_API_KEY', '123123123145' );
define( 'SUPPORT_MONITOR_SERVER_URL', 'https://example.org' );
```
1. Test out the settings for support monitor settings as part of this plugin on both a network activated multisite installation and a single site installation.
2. Check by defining various combinations of all or some of the constants in the `wp-config.php` and reviewing the Support Monitor Settings. …
> #161 - Allow defining support monitor constants to override settings.

- includes/classes/SupportMonitor/Monitor.php
VIP environments return `false` for object cache, causing Monitor to flag them as failing. Since VIP is a managed host that always has object caching enabled, we can safely return true if we can confirm that it’s a VIP env. This can be done via the VIP_GO_APP_ENVIRONMENT const as per https://docs.wpvip.com/infrastructure/environments/environment-specific-code/
* Fixed - Issue with cache returning false on VIP environments.
Props @darylldoyle, @joshuaabenazer
> 🐛 Fix issue with VIP environments

- 10up-experience.php
- CHANGELOG.md
Bumping the versions for the 1.15.0 release
> Prepare Release

- includes/classes/SSO/SSO.php
Minor update to button padding.
- Install the plugin
- Go to the admin login
- View / inspect the Fueled SSO button
- Fixed - button padding
Props @Firestorm980
> Fix: Fueled SSO Button Styles (r2)
